[tool.black]
line-length = 100
target-version = ['py35']

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_localfolder = "pytest_stoq,tests"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
