version: 2
workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
        - image: cprov/stoq:latest
        - image: circleci/postgres:9.5

    environment:
        STOQLIB_TEST_HOSTNAME: "localhost"
        STOQLIB_TEST_DBNAME: "test"
        STOQLIB_TEST_USERNAME: "postgres"
        STOQLIB_TEST_PASSWORD: ""

    steps:
      - checkout

      - run:
          name: Install test dependencies
          command: |
            git clone https://github.com/stoq/stoq.git
            easy_install3 pip
            pip install -U setuptools pip
            pip install -e stoq --no-deps
            pip install -r requirements-test.txt
            pip install -e .

      - run:
          name: Linters
          command: |
            pre-commit run -a
