version: 2
workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
        - image: circleci/python:3.5.7

    steps:
      - checkout

      - run:
          name: Install test dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 isort pre-commit pytest pytest-cov

      - run:
          name: Linters
          command: |
            . venv/bin/activate
            pre-commit run -a
